import React, { createContext, useContext, useState, useCallback, useMemo, useRef } from "react";
import { trpc } from "@/lib/trpc";
import { useEbpfStream } from "@/hooks/useEbpfStream";
import type { BpfProgram, BpfMap, EbpfSnapshot, ProgHistory, ActivitySummary } from "../../../shared/ebpf-types";

export type { StreamStatus } from "@/hooks/useEbpfStream";

/** The three operating modes of the app */
export type AppMode = "live" | "demo" | "snapshot";

export interface SnapshotMeta {
  filename: string;
  capturedAt: string;
  hostname: string;
  kernelVersion: string;
}

interface EbpfContextValue {
  snapshot: EbpfSnapshot | null;
  isLoading: boolean;
  error: string | null;
  selectedProgram: BpfProgram | null;
  setSelectedProgram: (p: BpfProgram | null) => void;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  typeFilter: string[];
  setTypeFilter: (types: string[]) => void;
  filteredPrograms: BpfProgram[];
  /** SSE stream status — replaces the old autoRefresh boolean */
  streamStatus: import("@/hooks/useEbpfStream").StreamStatus;
  /** Legacy compat: true when stream is live */
  autoRefresh: boolean;
  setAutoRefresh: (v: boolean) => void;
  refreshInterval: number;
  setRefreshInterval: (ms: number) => void;
  refresh: () => void;
  demoMode: boolean;
  /** Current operating mode */
  appMode: AppMode;
  /** Metadata about the loaded snapshot (only set in snapshot mode) */
  snapshotMeta: SnapshotMeta | null;
  /** Load a snapshot JSON file into snapshot mode */
  loadSnapshot: (file: File) => Promise<void>;
  /** Clear the loaded snapshot and return to live/demo mode */
  clearSnapshot: () => void;
  /** Map from program ID → ProgHistory (ring buffer data) */
  historyMap: Map<number, ProgHistory>;
  /** Activity summary — top programs by calls/sec */
  activity: ActivitySummary | null;
  statsEnabled: boolean;
  /** BPF maps — pushed via SSE stream, updated on every poller tick */
  maps: BpfMap[];
}

const EbpfContext = createContext<EbpfContextValue | null>(null);

export function EbpfProvider({ children }: { children: React.ReactNode }) {
  const [selectedProgram, setSelectedProgram] = useState<BpfProgram | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState<string[]>([]);
  // refreshInterval is kept for the Settings page UI but no longer drives polling
  const [refreshInterval, setRefreshInterval] = useState(5000);

  // ── Snapshot mode state ────────────────────────────────────────────────────
  const [loadedSnapshot, setLoadedSnapshot] = useState<EbpfSnapshot | null>(null);
  const [snapshotMeta, setSnapshotMeta] = useState<SnapshotMeta | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  // ── SSE live stream ────────────────────────────────────────────────────────
  const {
    snapshot: liveSnapshot,
    maps: liveMaps,
    allHistories,
    activity,
    status: streamStatus,
  } = useEbpfStream();

  // ── Poller status (for statsEnabled flag) — lightweight 30s poll ──────────
  const { data: pollerStatus, refetch } = trpc.ebpf.status.useQuery(undefined, {
    refetchInterval: 30_000,
    staleTime: 15_000,
  });

  // ── Active snapshot: loaded snapshot takes priority over live stream ───────
  const snapshot = loadedSnapshot ?? liveSnapshot ?? null;
  const maps: BpfMap[] = loadedSnapshot ? [] : liveMaps;

  const isLoading = loadedSnapshot === null && liveSnapshot === null && streamStatus === "connecting";

  // Manual refresh: trigger an immediate server-side poll via tRPC mutation
  const refreshMutation = trpc.ebpf.refresh.useMutation();
  // Server-side snapshot parser for raw bpftool format (capture-snapshot.sh output)
  const parseSnapshotMutation = trpc.ebpf.parseSnapshot.useMutation();
  const refresh = useCallback(() => {
    if (loadedSnapshot) return; // no-op in snapshot mode
    refreshMutation.mutate();
    refetch();
  }, [refreshMutation, refetch, loadedSnapshot]);

  // ── Snapshot loading ───────────────────────────────────────────────────────
  const loadSnapshot = useCallback(async (file: File) => {
    const text = await file.text();
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      throw new Error("Invalid JSON file");
    }

    const obj = parsed as Record<string, unknown>;

    // Two supported formats:
    // 1. UI export / capture-snapshot.sh with _ebpfVizSnapshot:true and a "snapshot" key
    //    (full pre-parsed EbpfSnapshot — can be used directly)
    // 2. capture-snapshot.sh with "raw" key (raw bpftool outputs — server-side parsing needed)
    //    For now we support format 1 only; format 2 requires server-side parsing.
    if (!obj._ebpfVizSnapshot) {
      throw new Error("Not a valid eBPF Viz snapshot file.\nExpected a file exported from eBPF Viz or generated by capture-snapshot.sh.");
    }

    let ebpfSnapshot: EbpfSnapshot;

    if (obj.snapshot && typeof obj.snapshot === "object") {
      // Format 1: pre-parsed snapshot embedded in the file
      ebpfSnapshot = obj.snapshot as EbpfSnapshot;
    } else if (obj.raw && typeof obj.raw === "object") {
      // Format 2: raw bpftool outputs — send to server for parsing via parseSnapshot mutation
      const rawObj = obj.raw as Record<string, unknown>;
      ebpfSnapshot = await parseSnapshotMutation.mutateAsync({
        raw: {
          progs: (rawObj.progs as unknown[]) ?? [],
          maps: rawObj.maps as unknown[] | undefined,
          net: rawObj.net as unknown[] | undefined,
          cgroups: rawObj.cgroups as unknown[] | undefined,
        },
        hostname: obj.hostname as string | undefined,
        kernelVersion: obj.kernelVersion as string | undefined,
        bpftoolVersion: obj.bpftoolVersion as string | undefined,
        capturedAt: obj.capturedAt as string | undefined,
        timestamp: obj.timestamp as number | undefined,
      });
    } else {
      throw new Error("Snapshot file is missing the 'snapshot' or 'raw' field.");
    }

    const capturedAt = (obj.capturedAt as string) ?? new Date(ebpfSnapshot.timestamp).toISOString();
    setLoadedSnapshot(ebpfSnapshot);
    setSnapshotMeta({
      filename: file.name,
      capturedAt,
      hostname: ebpfSnapshot.hostname ?? "unknown",
      kernelVersion: ebpfSnapshot.kernelVersion ?? "unknown",
    });
  }, [parseSnapshotMutation]);

  const clearSnapshot = useCallback(() => {
    setLoadedSnapshot(null);
    setSnapshotMeta(null);
  }, []);

  // ── Derived mode ───────────────────────────────────────────────────────────
  const appMode: AppMode = loadedSnapshot
    ? "snapshot"
    : (snapshot?.demoMode ? "demo" : "live");

  // Build a Map<id, ProgHistory> for O(1) lookup in components
  const historyMap = useMemo(() => {
    const m = new Map<number, ProgHistory>();
    if (allHistories) {
      for (const h of allHistories) m.set(h.id, h);
    }
    return m;
  }, [allHistories]);

  // Filter programs based on search + type filter
  const filteredPrograms = useMemo(() => {
    if (!snapshot) return [];
    let progs = snapshot.programs;

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      progs = progs.filter(p =>
        p.name.toLowerCase().includes(q) ||
        p.rawType.toLowerCase().includes(q) ||
        p.tag.toLowerCase().includes(q) ||
        String(p.id).includes(q) ||
        p.attachments.some(a => a.detail.toLowerCase().includes(q))
      );
    }

    if (typeFilter.length > 0) {
      progs = progs.filter(p => typeFilter.includes(p.rawType));
    }

    return progs;
  }, [snapshot, searchQuery, typeFilter]);

  // Legacy compat shim — components that read autoRefresh get true when live
  const autoRefresh = appMode !== "snapshot" && (streamStatus === "live" || streamStatus === "reconnecting");
  const setAutoRefresh = useCallback((v: boolean) => {
    // No-op: SSE manages its own connection lifecycle.
    // Kept for API compatibility with SettingsView and EbpfLayout.
    void v;
  }, []);

  return (
    <EbpfContext.Provider value={{
      snapshot: snapshot ?? null,
      isLoading,
      error: appMode !== "snapshot" && streamStatus === "offline" ? "Stream disconnected — check server" : null,
      selectedProgram,
      setSelectedProgram,
      searchQuery,
      setSearchQuery,
      typeFilter,
      setTypeFilter,
      filteredPrograms,
      streamStatus,
      autoRefresh,
      setAutoRefresh,
      refreshInterval,
      setRefreshInterval,
      refresh,
      demoMode: appMode === "demo",
      appMode,
      snapshotMeta,
      loadSnapshot,
      clearSnapshot,
      historyMap,
      activity: activity ?? null,
      statsEnabled: pollerStatus?.statsEnabled ?? false,
      maps,
    }}>
      {children}
    </EbpfContext.Provider>
  );
}

export function useEbpf() {
  const ctx = useContext(EbpfContext);
  if (!ctx) throw new Error("useEbpf must be used within EbpfProvider");
  return ctx;
}
